#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
putio-cli

Usage:
  putio-cli --oauth_token=<token> [options] <command> [<args>...]

General options:
  -h --help                 show help message and exit
  --version                 show version and exit
  -v --verbose              print status messages
  --oauth_token=<token>     use token to identify user

See putio-cli <command> --help for more information on a specific command.
"""

import sys
from inspect import getmembers, isclass, cleandoc
from docopt import docopt
from putio_cli import __version__ as VERSION


def main():
    """Main CLI entrypoint."""
    import putio_cli.commands as commands
    options = docopt(__doc__, version=VERSION, options_first=True)

    # get command arg
    cmd = options['<command>']

    # test if method exists
    if hasattr(commands, cmd):
        module = getattr(commands, cmd)
        commands = getmembers(module, isclass)
        command = [command[1] for command in commands if command[0] != 'Base'][0]

        # update options with submodule docstring
        docstring = cleandoc(command.__doc__)
        if 'Usage:' in docstring:
            options.update(docopt(docstring, argv=sys.argv[sys.argv.index(cmd):]))

        # define command and run it
        command = command(options)
        command.run()

    else:
        print "This command '%s' doesn't exist, try `putio-cli --help`" % cmd
        sys.exit(1)


if __name__ == '__main__':
    main()
